# ===========================
# Weekly iGaming Digest – Sources (UK Focus)
# ===========================

focus:
  region: "United Kingdom"
  country_codes: ["GB", "UK"]
  # מילים שמאותתות על רלוונטיות ל-UK
  keywords:
    - uk
    - united kingdom
    - great britain
    - gb
    - ukgc
    - gambling commission
    - asa
    - cap
    - dcms
    - remote gambling
    - online casino
    - slots
    - poker
    - bingo
    - affordability checks
    - stake limits
    - statutory levy
    - safer gambling
    - igaming uk
    - uk online casino
  # חברות/מותגים דומיננטיים ב-UK
  companies:
    - bet365
    - flutter
    - entain
    - william hill
    - 888 holdings
    - betfred
    - kindred
    - unibet
    - sky betting
    - sky vegas
    - rank group
    - grosvenor
    - mecca bingo
    - tombola
    - buzz bingo
    - paddy power
    - betway
    - games global
    - light & wonder
    - playtech
    - pragmatic play
    - evolution
    - relax gaming
    - push gaming
    - blueprint gaming
    - inspired entertainment
    - microgaming
    - white hat gaming
    - progressplay
  # סיומות דומיין מועדפות ל-UK (הקוד משתמש בשדה הזה)
  domain_suffixes: [".co.uk", ".uk", ".gov.uk", ".org.uk"]

  # דומיינים מועדפים (לא חובה, רק כהכוונה)
  domains_prefer:
    - gamblingcommission.gov.uk
    - asa.org.uk
    - cap.org.uk
    - gov.uk
    - parliament.uk
    - bbc.co.uk
    - theguardian.com
    - sbcnews.co.uk
    - casinobeats.com
    - slotbeats.com
    - igamingbusiness.com

# מילות מפתח לאירועים "גדולים" (יכנסו גם אם לא UK-טי)
major_keywords:
  - merger
  - acquisition
  - ipo
  - funding
  - investment
  - partnership
  - fine
  - penalty
  - sanction
  - enforcement
  - regulation
  - law
  - legislation
  - stake limit
  - affordability check
  - statutory levy
  - responsible gambling
  - white paper
  - market exit
  - market entry
  - product launch
  - uk launch

# ---------------------------
# News (RSS) – iGaming UK
# ---------------------------
news_rss:
  # iGaming trade media
  - https://casinobeats.com/feed
  - https://slotbeats.com/category/developer/feed
  - https://igamingbusiness.com/company-news/feed
  # מדיה/רגולציה UK
  - https://www.theguardian.com/society/gambling/rss
  # בינגו UK
  - https://bingodaily.co.uk/feed
  # כלל-ענפי (אירופה/גלובלי – יכללו רק אם "גדולים")
  - https://europeangaming.eu/portal/feed/
  - https://www.gamblingnews.com/feed/

# ---------------------------
# Poker & Bingo (RSS)
# ---------------------------
poker_rss:
  - https://www.cardplayer.com/poker-news.rss
  - https://www.pokerfuse.com/news/feed/
  # אפשר להוסיף ערוצים ספציפיים של PokerNews אם תרצה

bingo_rss:
  - https://bingodaily.co.uk/feed

# ---------------------------
# Games & Releases (RSS)
# משמש לחיזוק סקשן ה-"5 משחקים". (הקוד גם מושך משחקים מ-news_rss)
# ---------------------------
games_rss:
  - https://slotbeats.com/category/developer/feed    # חיזוק לפיד משחקים
  - https://casinobeats.com/feed                     # משחרר כותרות על תכנים/לנצ'ים
  # אופציונלי – חדשות גיימינג כלליות (לגיבוי): 
  - https://www.rockpapershotgun.com/feed
  - https://www.eurogamer.net/feed
  - https://www.vg247.com/rss
  # שים לב: SlotCatalog אין להם RSS פומבי יציב – לכן לא נוסף כאן.

# ---------------------------
# Podcasts
# ---------------------------
podcasts_listennotes_queries:
  - iGaming UK
  - online casino UK
  - UK Gambling Commission
  - remote gambling UK
  - slots industry
  - bingo UK
  - poker UK
  - safer gambling UK
  - Playtech Evolution Pragmatic Play UK
  - Flutter Entain Bet365 UK

podcasts_rss:
  - https://feeds.transistor.fm/igaming-daily
  - https://feeds.captivate.fm/thegamblingfiles/
  - https://feeds.acast.com/public/shows/the-problem-gambling-podcast
