# ===========================
# Weekly iGaming Digest — Sources (UK Focus)
# ===========================

focus:
  region: "United Kingdom"
  country_codes: ["GB", "UK"]

  # Signals for UK relevance (used in scoring)
  keywords:
    - uk
    - united kingdom
    - great britain
    - britain
    - england
    - scotland
    - wales
    - ukgc
    - gambling commission
    - dcms
    - hm treasury
    - treasury
    - levy
    - duty
    - tax
    - remote gaming duty
    - statutory levy
    - affordability checks
    - stake limits
    - safer gambling
    - online casino
    - slots
    - poker
    - bingo
    - igaming
    - igaming uk
    - uk online casino

  # Operator / supplier names that boost UK relevance
  companies:
    - william hill
    - flutter
    - entain
    - ladbrokes
    - coral
    - 888
    - bet365
    - sky betting
    - paddy power
    - betfair
    - kindred
    - unibet
    - rank group
    - mecca bingo
    - buzz bingo
    - tombola
    - gamesys
    - betfred
    - virgin games
    # Suppliers (content / platforms)
    - softswiss
    - evolution
    - pragmatic play
    - playtech
    - light & wonder
    - scientific games
    - games global
    - blueprint gaming
    - relax gaming
    - red tiger
    - big time gaming
    - btg
    - yggdrasil
    - elk studios
    - nolimit city
    - hacksaw
    - push gaming
    - play'n go
    - quickspin

  # UK-ish domains (adds score if link ends with these)
  domain_suffixes: [".co.uk", ".uk", ".gov.uk", ".org.uk"]

  # Prefer/boost stories from these domains even if not .uk
  source_domains_prefer:
    - egr.global
    - softswiss.com
    - igamingbusiness.com
    - sbcnews.co.uk
    - casinobeats.com
    - slotbeats.com
    - europeangaming.eu
    - gamblingnews.com
    - yogonet.com
    - theguardian.com
    - bbc.co.uk
    - gamblingcommission.gov.uk
    - gov.uk

  # Nudge trends generator (only if supported by data)
  trend_hints:
    - gambling tax
    - remote gaming duty
    - levy
    - stake limits
    - affordability checks
    - illegal market
    - enforcement
    - white paper

# Items with these words are considered "major" even if not strongly UK
major_keywords:
  - tax
  - duty
  - levy
  - treasury
  - budget
  - merger
  - acquisition
  - ipo
  - funding
  - investment
  - partnership
  - fine
  - penalty
  - sanction
  - enforcement
  - regulation
  - law
  - legislation
  - licensing
  - stake limit
  - affordability check
  - market exit
  - market entry
  - product launch
  - uk launch

# ---------------------------
# News (RSS) — UK / iGaming
# ---------------------------
news_rss:
  - https://www.sbcnews.co.uk/feed/
  - https://www.casinobeats.com/feed/
  - https://slotbeats.com/category/developer/feed/
  - https://www.igamingbusiness.com/feed/
  - https://europeangaming.eu/portal/feed/
  - https://www.gamblingnews.com/feed/
  - https://www.theguardian.com/society/gambling/rss
  - https://www.theguardian.com/sport/betting/rss
  # Tip: EGR has limited public RSS. We inject key EGR URLs via `must_include.urls` below.

# ---------------------------
# Poker & Bingo (RSS)
# ---------------------------
poker_rss:
  - https://www.pokernews.com/rss/all.xml
  - https://www.cardplayer.com/poker-news.rss
  - https://www.pokerfuse.com/news/feed/

bingo_rss:
  - https://bingodaily.co.uk/feed
  - https://www.whichbingo.co.uk/news/feed/

# ---------------------------
# Games & Releases (RSS)
# Fuels the “🎮 Top Trending Games in England — 5 to Watch”
# ---------------------------
games_rss:
  - https://slotbeats.com/feed/
  - https://slotbeats.com/category/developer/feed/
  - https://www.casinobeats.com/category/slot-news/feed/

# Used only if we still lack 5 games (deeper lookback)
games_fallback_rss:
  - https://slotbeats.com/category/slot-releases/feed/
  - https://www.casinobeats.com/category/slot-developer-news/feed/

# ---------------------------
# Podcasts
# ---------------------------
podcasts_listennotes_queries:
  - "UK online casino regulation"
  - "remote gaming duty UK"
  - "igaming UK casino slots"
  - "UK Gambling Commission"
  - "safer gambling UK"
  - "Flutter Entain bet365 UK"
  - "Playtech Evolution Pragmatic Play UK"
  - "bingo UK"
  - "poker UK"

podcasts_rss:
  - https://feeds.transistor.fm/igaming-daily
  - https://feeds.captivate.fm/thegamblingfiles/
  - https://feeds.acast.com/public/shows/the-problem-gambling-podcast

# ---------------------------
# MUST INCLUDE (direct URLs)
# These URLs are injected even without RSS — great for EGR / paywalled / single pages.
# Replace/add each week as needed.
# ---------------------------
must_include:
  urls:
    - "https://www.egr.global/intel/news/bgc-ceo-gambling-tax-increases-wont-solve-anything/"
    # Example SOFTSWISS item — replace with the current week’s article URL:
    # - "https://www.softswiss.com/news/softswiss-announces-uk-focused-partnership-xyz/"
