name: Weekly iGaming Digest

on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday 08:00 UTC (09:00 London in BST)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAX_ITEMS_PER_SECTION: ${{ secrets.MAX_ITEMS_PER_SECTION }}
          LOOKBACK_DAYS: ${{ secrets.LOOKBACK_DAYS }}
          MAJOR_ONLY_NON_CASINO: ${{ secrets.MAJOR_ONLY_NON_CASINO }}
          LISTENNOTES_API_KEY: ${{ secrets.LISTENNOTES_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEETS_SPREADSHEET: ${{ secrets.SHEETS_SPREADSHEET }}
        run: python main.py
