name: Weekly iGaming Digest

on:
  schedule:
    - cron: '0 8 * * 1'   # Every Monday 08:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # sanity check that all required secrets exist before running the script
      - name: Preflight env
        run: |
          python - <<'PY'
          import os, sys
          required = [
            "OPENAI_API_KEY","OPENAI_MODEL","TO_EMAIL","FROM_EMAIL",
            "SMTP_SERVER","SMTP_PORT","SMTP_USER","SMTP_PASS"
          ]
          missing = [k for k in required if not os.getenv(k)]
          if missing:
            print("Missing secrets:", ", ".join(missing))
            sys.exit(1)
          print("Al
